CPPFLAGS=-Wall -O0 -g -I../src

tests: basename_test \
       strerror_test \
       string_to_number_test

clean:
	rm -f basename_test strerror_test string_to_number_test


#basename_test: basename_test.cpp


#strerror_test: strerror_test.cpp

